### ISSUE TITLE
Live link

### ISSUE THREAD

**Issue by PipHarsveld** [EvaZ7/happyhaven#1]
Je live link gaat nu nog naar de website van dit vak van de minor, dat moet je nog even aanpassen naar https://happyhaven.adaptable.app/

**Comment by Inevdhoven** [comment]
<img width="346" alt="Scherm­afbeelding 2023-04-21 om 10 50 08" src="https://user-images.githubusercontent.com/43877754/233591280-7a3fa44f-8b76-432b-8dfa-75a23a687d35.png">
Hier heb je nog niet je eigen link en eventueel een kleine intro geplaatst.

**Comment by MartijnvdLans** [comment]
![image](https://user-images.githubusercontent.com/74150653/233591947-fee01df9-1e1f-4e23-9c02-53d32ed176b2.png)

Hier kijk je ook snel overheen misschien is de volledige link handiger om neer te zetten onder een apart kopje zoals:

## Live demo
https://happyhaven.adaptable.app/
