### ISSUE TITLE
Bug met dubbele berichten

### ISSUE THREAD

**Issue by PipHarsveld** [EvaZ7/happyhaven#3]
Er zit een gekke bug in de chat waarbij soms de berichten dubbel getoond worden. Het lijkt alsof er een loopje met een tijd op staat, want eens in de zoveel tijd worden de berichten herhaald.

Afbeelding van het probleem:

![image](https://user-images.githubusercontent.com/54938035/233588452-f1e8d9bc-6a96-4244-ac7f-09662862ff40.png)

Context: 

Persoon A stuurt Hi, persoon B stuurt Test en deze berichten worden herhaald zonder dat de gebruiker deze berichten opnieuw verstuurd

**Comment by Inevdhoven** [comment]
Dit probleem ben ik ook tegen gekomen en heb ik zelf ook. Wanneer je een bericht stuurt en een ander persoon stuurt ook een bericht dan krijg je deze dubbel te zien en stuurt hij oudere berichten ook mee. Wanneer je even wacht dan blijft hij door de berichten loopen.

<img width="887" alt="Scherm­afbeelding 2023-04-21 om 10 53 29" src="https://user-images.githubusercontent.com/43877754/233592083-b31f2bd3-f30f-488d-9a8d-fc2b03a9100d.png">

**Comment by EvaZ7** [comment]
Ik heb dit opgelost!!!! Ligt aan 2 dingen....
1. Je moet alleen de history emitten individueel naar de socket id van een nieuwe gebruiker
2. Adaptable.... reconnect en disconnect steeds users uit zichzelf... :( dus railway is een beter alternatief
